import { UnitStory } from "@/lib/unit-story";

export const manualUnitStories: Record<string, UnitStory> = {
  "scholastic-g5-g5-u1-w1": {
    title: "Unit 1 Story",
    paragraphs: [
      "On Monday morning, Class 5B was lined up for the first school assembly when the principal ran onto the blacktop carrying a giant blue **receptacle（容器）**. He announced that it was the school's brand-new \"Suggestion Box Number Two.\" Before anyone could clap, Mason, the morning helper, tangled the microphone cord into a knot and made a huge **blunder（错误）**. The whole class wanted to laugh, but the principal **generally（通常）** hated loud laughter first thing in the morning, so everyone had to squeeze their faces still.",
      "Then Ethan, a complete **novice（初学者）** who had just joined our class, was asked to handle the morning announcements for the first time. He got so nervous that his hands began to **quiver（发抖）**, and instead of the welcome music, he played \"Happy Birthday.\" The old speaker beside the blacktop sounded terribly **hazardous（危险的）**, as if it might spit sparks every time it crackled. The PE teacher rushed around in panic and, without thinking, stepped onto a skateboard too **rash（草率地）**, flying straight into the flowerbed with his whistle.",
      "The wildest part came when the principal tried to **veto（否决）** the whole disaster, but the blue box suddenly popped open and announced in a radio voice, \"Today's chaos is truly **outstanding（突出的）**!\" It then explained very seriously that the school's plans were always a little **variable（多变的）**, and turning a ceremony into a comedy once in a while was simply part of campus culture. The class went quiet for three seconds, and then everyone laughed so hard that the next classroom probably thought we were raising a flock of ducks that could perform stand-up comedy."
    ]
  },
  "scholastic-g5-g5-u1-w2": {
    title: "Unit 2 Story",
    paragraphs: [
      "Early Wednesday morning, the school suddenly announced a \"Happiness Test.\" In the middle of the playground stood a huge pumpkin machine. Whoever stepped onto it would be judged as either happy or **blissful（幸福的）**. The cafeteria joined in by serving a **bountiful（丰盛的）** breakfast of pumpkin muffins, pumpkin pancakes, and cinnamon apples. Even the orange juice looked suspiciously festive. Only Owen, the new student, looked completely **bewildered（困惑的）**, because he had no idea why breakfast felt like a contest.",
      "Once the test officially began, everyone realized it was not as simple as it looked. The scoring machine was so **cumbersome（笨重的）** that four teachers had to push it beside the basketball hoops. Even more **daunting（令人发怵的）**, once it was turned on, it began beeping **ceaseless（不停的）** reminders: \"Please smile! Smile more happily!\" The sound was so loud that even the pigeons upstairs flew away together. In the corner, the pumpkin-rabbit mascot that had been **dormant（休眠的）** all morning slowly opened its eyes, as if it were ready to enjoy the show.",
      "The real trouble began in round three. The pumpkin rabbit suddenly hopped onto the scoring platform and pretended to help students earn points, but it was secretly changing the numbers. It turned out to be a very **treacherous（不可靠的）** little creature. It even declared that anyone who did not laugh loudly enough had to run ten laps around the field, which sounded absolutely **brutal（残忍的）**. The class was about to protest when the science teacher rushed up with a record sheet and proved that Owen's complaint was completely **valid（有效）**. The principal shut the machine down at once, and everyone went back to freely eating breakfast and telling jokes. Class 5B became truly **blissful（幸福的）** again, while the naughty rabbit had to sit by the door and reflect on its behavior while smelling pumpkin pancakes."
    ]
  },
  "scholastic-g5-g5-u1-w3": {
    title: "Unit 3 Story",
    paragraphs: [
      "On Invention Day, our homeroom teacher walked in and announced that the school would **allow（允许）** every student to bring one invention that was \"absolutely not ordinary\" to the auditorium. Lucas pushed up first with a robot that could automatically write praise letters. The moment it turned on, it started giving everyone a **compliment（夸奖）** in a broadcast voice. Even the janitor by the door received one: \"Your sweeping posture is very elegant today.\" The whole room burst into laughter.",
      "The excitement lasted only five minutes. Our student council rep began offering serious **criticism（批评）**, because although the robot was certainly **unique（独特的）**, its shell looked far too **flimsy（脆弱的）**, as if it had been built from cookie boxes and tape. Sure enough, it barely reached the edge of the stage before declaring that it was suffering from **fatigue（疲惫）**, sitting down with a plop, and demanding a cup of hot cocoa before continuing. The principal had thought the day would be an **ordinary（普通的）** exhibition, but by then he was already rubbing his temples.",
      "To stop the situation from getting worse, the vice principal quickly announced that the school would now **prohibit（禁止）** any invention that could breathe fire, spray water, or suddenly sing. Just when everyone thought the competition would end early, the robot stood back up. The little light on its chest blinked, and it burst with amazing **vigor（精力）**. First it straightened its not very **substantial（结实的）** body, then it praised every student's good points, and finally it handed the principal a note that said, \"Please sleep more and frown less.\" The auditorium fell silent for three seconds, and then everyone agreed: shabby as it looked, that robot was definitely the best invention of the day."
    ]
  },
  "scholastic-g5-g5-u1-w4": {
    title: "Unit 4 Story",
    paragraphs: [
      "This week the school invited a cat to serve as the \"Campus Manners Officer.\" When it first entered our classroom, it seemed wonderfully **considerate（体贴的）**. It neatly stacked the homework notebooks that the wind had blown around and gently carried dropped pencils back to students' desks. Everyone thought the whole event was very **interesting（有趣的）**, and even our always-serious math teacher praised the cat for being polite.",
      "But by second period, the cat suddenly turned extremely **frisky（活蹦乱跳的）**. It leaped onto the windowsill, crawled into the teacher's desk, and finally batted at the principal's tie as if it were a ball of yarn. At the same time, Mia, the classroom helper, was especially **heedless（粗心的）** and forgot to shut the side door. As a result, three geese that had wandered over from the park next to school waddled straight into the room and turned the once peaceful lesson into total confusion. Looking at feathers all over the floor, our teacher started wondering whether making the cat a **permanent（永久的）** school program had been a little **ridiculous（荒谬的）**.",
      "The strangest part was that the school turtle, who was usually the most **sluggish（慢吞吞的）** creature on campus, was the calmest in the emergency. It slowly crawled to the center of the room and announced that the most **sensible（明智的）** thing to do was to escort both the cat and the geese outside before the lesson became even more **tiresome（烦人的）**. Just as everyone was nodding in agreement, the decorative banner above us tilted and the display stand became dangerously **unstable（不稳定的）**. So the whole class sprang into action: some students held the stand, some chased the geese, and some carried the cat away. When order finally returned, the principal panted and said that the first lesson in manners today was simple: never underestimate an overexcited cat."
    ]
  },
  "scholastic-g5-g5-u1-w5": {
    title: "Unit 5 Story",
    paragraphs: [
      "The school decided to turn the old warehouse into a \"Future Gym,\" and early in the morning the principal spread a huge **blueprint（蓝图）** across the teacher's desk. He carefully introduced the new features: an automatic scoreboard, cheering stands, and even a special lane for mascots to run through. Everyone listened with shining eyes when the floor suddenly trembled, like a tiny **earthquake（地震）**, shaking the chalk dust into little white clouds.",
      "The PE teacher hurriedly opened the construction **guidebook（指南）** to check whether we should evacuate or cut the electricity first. To his surprise, the temporary **headquarters（指挥部）** had been set up on a folding table by the back door of the warehouse, right beside the school garden. The art teacher had tried to create the mood of a champion's lounge and had decorated the place like a mini stadium snack bar. While everyone was running around in confusion, Jake from the football club suddenly grabbed a ball and charged forward to prove that the gym already worked. To everyone's shock, he actually scored a perfect **touchdown（达阵）**.",
      "What really silenced the room was the giant new **windshield（挡风玻璃）** installed at the front of the warehouse. Once the sunlight hit it, it glowed like a movie screen and left everyone **spellbound（入迷的）**. But a second later, the test fountain in the middle of the hall spun into a little **whirlpool（漩涡）**, sucking the principal's blueprint into a swirl of paper. We all thought we were about to be scolded, but after chasing the pages for two full laps, the principal stopped, looked up, and declared, \"If a place can perform a construction demo, a football game, and a disaster movie at the same time, it already counts as a **masterpiece（杰作）**.\" The room froze for a second, then burst into laughter so loud that even the pigeons on the roof seemed to flap in agreement."
    ]
  },
  "scholastic-g5-g5-u1-w6": {
    title: "Unit 6 Story",
    paragraphs: [
      "This week the auditorium was borrowed for rehearsals of a grand **bridal（婚礼的）** fairy-tale play. The art team had just rolled in the fake wedding cake when the prop horse playing the white steed suddenly went wild. Its **bridle（缰绳）** had been tied backward. The wooden horse charged across the stage and smashed a huge hole in the foam arch, which had already been made a little **coarse（粗糙的）**, sending the flower children running away with their plastic roses.",
      "The director waved her notebook and shouted for everyone to continue according to the planned **course（流程）**. But the backstage **crews（工作人员）** had clearly decided to stop behaving. One person was pouring soap into the mist machine, another was loading confetti cannons onto a trolley, and two others were secretly pushing the swan boat prop into the hallway for a lunchtime **cruise（巡游）**. To save the performance, the music teacher grabbed a **lute（鲁特琴）** and tried to calm the chaos with classical music.",
      "But halfway through the second tune, the speakers burst out with a **foul（刺耳又糟糕的）** scream so awful that even the prop **fowl（家禽）** goose by the door flapped in terror. It snatched the treasure box full of fake coins and dragged all the glitter and plastic jewels into the flowerbed as if they were **loot（战利品）**. In the end, the entire class had to crouch in the grass searching for \"gold,\" while the director sighed and said, \"The most realistic thing about this wedding play is not the romance. It's the fact that everyone is desperately trying to rescue it.\""
    ]
  },
  "scholastic-g5-g5-u1-w7": {
    title: "Unit 7 Story",
    paragraphs: [
      "During Health Week, the school invited a parrot that could recite an entire health handbook. But as soon as it stepped on stage, we noticed that this **invalid（病人）** parrot was wrapped in bandages itself, coughing while bravely trying to give a speech. Even worse, the first poster it brought was also **invalid（无效的）**, because it had printed \"Drink eight glasses of water every day\" as \"Drink eight glasses of ink every day.\" Even the first graders stared in disbelief.",
      "The principal was trying to rescue the event when the broadcasting room delivered a glowing hat as a **present（礼物）**. Unfortunately, the student speaker who was supposed to host the program had not yet **present（出席）** himself, so everyone simply placed the hat on the podium and let it speak instead. The hat talked seriously for one whole **minute（分钟）**, then added, \"By the way, the principal's patience is very **minute（极小的）**, so please stop asking whether ink can replace milk.\" The entire auditorium nearly collapsed from laughter.",
      "At that very moment, a testing **object（物体）** on the science table suddenly stood upright and announced that it **object（反对）**ed to this overly chaotic health lecture. The janitor rolled in to collect the **refuse（垃圾）**, but the principal thought she meant to **refuse（拒绝）** his instructions and almost dropped the loudspeaker. In the end, the flashing hat remained the calmest thing in the room. It concluded with one sentence: \"A truly healthy school is not a school without chaos. It is a school where someone still remembers to clean up the trash during the chaos.\""
    ]
  },
  "scholastic-g5-g5-u1-w8": {
    title: "Unit 8 Story",
    paragraphs: [
      "On the opening day of International Performance Week, the backstage area of the auditorium looked like a costume warehouse that had completely lost its mind. The drama club had planned a seaside dance, but the costume teacher spent ten minutes arguing over whether the lead actor should wear a **bikini（比基尼）** or a **tuxedo（燕尾服）**. In the end, she decided he should wear formal clothes on top and beach shorts on the bottom, calling it \"cool but elegant.\" Meanwhile, the sound engineer stood in the makeup room chewing **bologna（博洛尼亚香肠）** and spraying **cologne（古龙水）**, making the whole backstage smell like a singing bar of soap.",
      "Things became even more absurd when the prop team carried in a giant **cantaloupe（哈密瓜）** to serve as the centerpiece of the stage. Next to it they placed several cans of **sardines（沙丁鱼）**, claiming that a beach theme needed seafood. But just as rehearsal began, a **tarantula（狼蛛）** slowly crept out from under the tablecloth. The host screamed, jumped onto the piano, and nearly turned the opening song into the soundtrack of a horror movie.",
      "To keep the whole school from thinking the day had become an insect exhibition, the principal urgently changed the program into a playground **marathon（马拉松）** watermelon chase. Whoever caught the rolling cantaloupe first would be the winner. The art teacher chased after it while doing tiny **vaudeville（杂耍喜剧）** steps, took a sharp turn, crashed into a basket of **tangerine（橘子）**, and rolled straight into the fountain. By the time everyone had rescued the melon, the oranges, and the teacher, applause was already spreading outside the hall. The whole school agreed that the performance had been a disaster, but a very unforgettable one."
    ]
  },
  "scholastic-g5-g5-u1-w9": {
    title: "Unit 9 Story",
    paragraphs: [
      "Global Food Day began with a tail-wagging **alligator（短吻鳄）** balloon standing at the cafeteria entrance. Its mouth puffed out tomato-scented bubbles as if it were advertising the day's menu. Beside it stood a **bandit（强盗）** doll with a black eye patch guarding the door. Anyone who wanted to go in for lunch had to hear it shout, \"Praise the chef three times first, or no entry!\"",
      "Inside the kitchen, things looked even stranger. The **barbecue（烧烤）** grill sizzled loudly, a bowl of **okra（秋葵）** had been arranged like a crown, and the teacher on duty came out wearing a **kimono（和服）** while carrying a teapot of rainbow-bubbling **syrup（糖浆）**. The principal sat down in a corner and tried to quietly read a **magazine（杂志）**, but it suddenly started flipping its own pages and rating the dishes with stars. Annoyed, he had to turn it upside down on his tray.",
      "At the noisiest moment, a little electric cart shaped like an **impala（黑斑羚）** rolled in from outside. Standing on top was a third grader dressed as a **sheik（酋长）**, still wearing moon-patterned **pajamas（睡衣）**. Waving a soup ladle, he announced that the mysterious dessert of the day would be tasted first by the \"alligator chef.\" Everyone laughed and applauded, and even the pickiest eaters had to admit that this ridiculous lunch was far more memorable than any normal meal."
    ]
  },
  "scholastic-g5-g5-u1-w10": {
    title: "Unit 10 Story",
    paragraphs: [
      "On the day of graduation rehearsal, an absurdly long **limo（豪华轿车）** was parked outside the auditorium, and the driver was a flamingo wearing sunglasses. When the door opened, a stylish **coed（男女同校学生）** dressed like a news anchor stepped out first, followed by a trembling robot **grad（毕业生）**. The students gathered along the red carpet and clapped like excited **fan（粉丝）**s at a real awards show.",
      "Backstage, things were even more dramatic. The drama club **champ（冠军）** was decorating the stage with a pile of **curio（小古玩）** objects, including a fake owl that could turn its head. The art teacher held a **mike（麦克风）** and kept warning everyone not to step on the formal gowns. Then a sports **ref（裁判）** suddenly rushed in and insisted that the ceremony had to be run like a game, with first half and second half, and maybe even whistles to decide who should receive a certificate first.",
      "The principal was getting desperate, so he went looking for an older **rev（受尊敬的人）** from the neighboring school to save the event. But the poor man had just climbed into a borrowed **taxi（出租车）** when the flamingo driver took him for a ride around the playground and somehow bought three milkshakes on the way. In the end, the robot stood in the auditorium holding the microphone and calmly announced, \"The most important thing today is not whether the program is perfect. It is that everyone has tried hard to grow up.\" The room actually fell silent for two whole seconds, and then everyone burst into laughter again because the flamingo hit the horn by mistake."
    ]
  },
  "scholastic-g5-g5-u1-w11": {
    title: "Unit 11 Story",
    paragraphs: [
      "On the opening day of Science Week, a bright **flare（闪光信号）** suddenly flashed across the ceiling of the auditorium, as if someone on the roof were sending a secret distress call. Before anyone could recover, a wild **flurry（突然的一阵乱动）** of wind rushed through the doorway and sent the principal's speech pages flying everywhere. Strangest of all, a tiny **glimmer（微光）** kept shining through a crack in the curtain, making it look as though some mysterious machine was hiding behind the stage.",
      "The science teacher followed the light and discovered a brand-new **spacelab（太空实验室）** model backstage, complete with blinking test tubes and a toy monkey in a white coat. But the moment it was switched on, alarms began ringing. The broadcasting room tried to sound calm and announced a **medevac（医疗后送）** drill to rescue \"a frightened eraser.\" Then, as if that were not enough, a squad of toy **paratroops（伞兵部队）** drifted down onto the playground flowerbed on tiny parachutes, looking as though they had arrived for a secret mission.",
      "The art room side of the hall became the noisiest of all. Someone spilled paint and made a huge **splatter（飞溅的斑点）** on the wall. Ducks outside began to **squawk（尖声叫喊）** in alarm. The science teacher sketched a quick diagram on the board, and one crooked **squiggle（弯曲线条）** actually started wriggling by itself. At last the principal held his forehead and declared that the school now needed to hold a **telethon（电视募捐马拉松）**, because if we did not buy better equipment soon, the auditorium might truly launch itself into space."
    ]
  },
  "scholastic-g5-g5-u1-w12": {
    title: "Unit 12 Story",
    paragraphs: [
      "On Nature Observation Day, the school turned the playground into an \"Animal Group Word Park.\" In the flowerbeds there was first a **bed（一片）** of tulips, and beside it an orderly ant **colony（群落）** marching away with half a cookie that nobody could explain. At first everyone thought the day would be peaceful, but before first period even ended, things had already become ridiculous.",
      "A loud **gaggle（鹅群）** of geese suddenly appeared beside the pond, honking as they marched along. In the corner of the field, a few boys arguing over a new soccer ball quickly formed a little **gang（一伙人）**. Even better, several foxes were crouched behind the bushes in a quiet **skulk（狐狸群）**, as if they were secretly attending the school assembly. The broadcasting teacher got so excited that she almost invited a **company（一群）** of parrots into the studio to read the lunchtime news.",
      "By lunchtime, the gate area had grown even busier. A **string（一列）** of ponies stood in a row, a **knot（一群）** of toads hopped by the flowerbed, a **school（一群）** of goldfish crowded the pond, and even a **troop（一队）** of kangaroos stood in a line more neatly than most students. The principal opened his mouth to end the activity, but after seeing that the animals were better at lining up than fifth graders, he changed his speech and admitted that the best lesson in discipline that day had probably come from the kangaroos."
    ]
  },
  "scholastic-g5-g5-u1-w13": {
    title: "Unit 13 Story",
    paragraphs: [
      "On the day of the geography model show, the floor of the auditorium was covered with a giant map, and the air smelled strangely of jelly and cardboard. At the entrance there was a row of **archipelago（群岛）** cookies. Beside it, a chocolate river flowed slowly toward a blob of mud shaped like a **delta（三角洲）**. We had barely walked in before it felt as if we had wandered into a geography book that somehow tasted sweet.",
      "Farther inside, the third graders had built a deep **gorge（峡谷）** out of cardboard boxes. Nearby, a narrow **isthmus（地峡）** connected two large platforms. The art team wrapped the edge of the stage into a **peninsula（半岛）**, and at the end of the hallway they created a tiny **oasis（绿洲）** complete with toy palm trees and drink umbrellas, like a cold drink stand for travelers lost in the desert. One raised platform became a **plateau（高原）**, while a dip in the carpet turned into a **valley（山谷）** that made the first graders lie on the floor and stare at it with delight.",
      "For the grand finale, the science teacher carved a blue **strait（海峡）** through a tray of jelly and added a **tributary（支流）** beside it to complete the map. The principal stood nearby nodding with great interest, but just as he began to comment, he slipped and rolled down the \"valley\" toward the \"strait,\" nearly knocking over the entire cookie island chain. The hall went silent for one second and then exploded with laughter, because everyone agreed that nothing could help students remember landforms better than watching the principal fall right into one."
    ]
  },
  "scholastic-g5-g5-u1-w14": {
    title: "Unit 14 Story",
    paragraphs: [
      "On Poetry Festival Day, our language teacher entered the room and announced that no one was allowed to win by simply memorizing model poems. We had to rely on imagination. She wrote a set of **rhyme（押韵词）** words on the board and had us tap our desks to find the **meter（节奏）**. Then the backpack in the front row, the one stuffed with half a box of crayons, started thumping along by itself and nearly turned the whole class into a dance troupe.",
      "When it was time to create poems, our student council rep wrote a **simile（明喻）**, saying the principal's shiny head was as bright as the moon. Not to be outdone, the assistant rep added a **couplet（对句）** that described this moon as a pancake that frowned during morning announcements. The art teacher got so excited that she made the blackboard complain about eating chalk dust all day, which helped everyone remember **personification（拟人）** at once.",
      "Later, students took turns trying **haiku（俳句）**, **metaphor（隐喻）**, and **alliteration（头韵）**. Even the first graders in the corner were practicing **onomatopoeia（拟声词）**, banging their lunchboxes while writing sound words. At the end, the principal decided to close the event by reading a **sonnet（十四行诗）** himself. He meant to amaze the audience, but when he reached line six, a real thunderous rumble sounded outside the window, and suddenly no one could tell whether it was weather or simply the poetry contest reaching its most dramatic moment."
    ]
  },
  "scholastic-g5-g5-u1-w15": {
    title: "Unit 15 Story",
    paragraphs: [
      "On Friday at lunch break, the storage locker of Class 5B suddenly popped open, and out rolled a tin box labeled **doodad（小玩意儿）**. While everyone gathered around in **chitchat（闲聊）** trying to guess what was inside, the lid flew open with a snap and a singing spoon and a blinking eraser sprang out. Our student council rep shouted **fiddlesticks（胡说；哎呀）**, but by then nobody wanted to close the box again.",
      "In less than five minutes, the whole classroom had become a **hodgepodge（大杂烩）**. Jump ropes wrapped around rulers, erasers chased chalk, and a globe somehow ended up wearing a lunchbox lid as a hat. Noah stood there completely **flabbergast（惊呆了）**, but Caleb remained by the door **lollygag（磨磨蹭蹭）**ing, eating jelly and asking whether we should first decide who ought to call the teacher. The classroom cleanup captain was furious and said he was far too **namby-pamby（软弱没主见）** for a moment like this.",
      "Then a burst of **hullabaloo（大吵大闹）** came from the broadcasting room. The whole class rushed outside and found a duck in the middle of the playground announcing itself as a **rapscallion（小捣蛋鬼）** while using a pointer to explain the **nitty-gritty（核心细节）** of school management on the board. The principal was ready to send it away, but the duck handed over a discipline report even more detailed than a teacher's. By the end of the day, everyone agreed that the most absurd yet strangely talented thing on campus had not been the tin box at all, but that extremely serious duck."
    ]
  },
  "scholastic-g5-g5-u1-w16": {
    title: "Unit 16 Story",
    paragraphs: [
      "On Root Word Day, the teacher had barely opened the classroom door when a **biped（两足动物）** turkey wearing a tiny vest marched in like the special guest of the day. It hopped onto the podium and demanded that our student council rep **enumerate（逐条列举）** all of today's ridiculous plans, including a singing blackboard, a self-scoring eraser, and a rule banning bananas from sitting in on math lessons. By then, the whole class was already trying not to laugh.",
      "Then the principal entered carrying a display board covered in numbers and announced that from now on the school would adopt more **liberal（宽松的）** classroom rules, because true **liberty（自由）** meant students should be free to think and ask questions, even about whether a watermelon deserved to enter a poetry recital. The math teacher was about to object when the **numeral（数字符号）**s on the board started jumping around on their own and fighting over who should stand above the fraction line. In the end, the biggest 7 plopped itself into the place of the **numerator（分子）** as if it had won a crown.",
      "By third period, things were even livelier. **Numerous（许多）** little paper figures had gathered outside the auditorium, pumping a **pedal（踏板）** organ as they lined up to listen to class. The trophy had been placed neatly on a **pedestal（底座）**, as if waiting to reward the noisiest prop of the day. Even the **pedestrian（行人）** sign by the door, which normally just reminded people to walk carefully, suddenly made a stern speech about keeping right in the hallway and speaking softly. The class stared for a moment and then quietly agreed that the most teacher-like thing in the room that day might not have been a human at all."
    ]
  },
  "scholastic-g5-g5-u1-w17": {
    title: "Unit 17 Story",
    paragraphs: [
      "At the beginning of Broadcasting Studio Open Day, the language teacher first asked everyone to **clarify（澄清）** one thing: today we were allowed to look at the equipment, but absolutely not to use the microphone as a rocket launcher. The moment she finished speaking, a **clarion（高而清亮的号角声）** blast rang out from outside, sending the pigeons by the auditorium flapping into the air and making even the principal cover his ears.",
      "To keep the visit full of **clarity（清晰）**, our student council rep immediately held up a **declaration（声明）** and **declare（宣布）**d that anyone who touched the control panel without permission would have to peel carrots in the cafeteria. The assistant rep disagreed and insisted on using a recorder so he could **dictate（口述）** his speech. Unfortunately, the recorder began speaking like a tiny **dictator（独裁者）**, ordering the whole class to stand up, sit down, and stand up again as if we were doing bizarre radio calisthenics.",
      "The best part was the **dictionary（词典）** in the corner. It suddenly flipped itself open and corrected everyone's **diction（措辞和发音）** in the clearest voice imaginable. Then it solemnly **predict（预言）**ed, \"In ten minutes, the principal will spill grape juice on his sleeve.\" We had barely started laughing when the principal rushed in holding up a purple-stained sleeve. The whole room went silent for one second, and then the loudest applause of the day was given to a dictionary that could both teach pronunciation and tell the future."
    ]
  },
  "scholastic-g5-g5-u1-w18": {
    title: "Unit 18 Story",
    paragraphs: [
      "At the start of the science fair, the weather group placed a **barometer（气压计）** by the door and solemnly announced that the air today contained not only changes in pressure but also the scent of strawberry pudding. The math group refused to be outdone and wheeled in a giant disk model to demonstrate how the **diameter（直径）** passed through the exact center of a circle. The lesson had barely begun when the first graders started spinning it like a game wheel and nearly made the teacher dizzy.",
      "The **kilometer（公里计）** step counter by the playground also decided it wanted attention. It switched itself on and loudly announced how far everyone had walked that day, then began reciting multiplication tables. The **mechanic（机械师）** teacher had just crouched down to inspect it when the robot assistant proudly declared that it would **mechanize（使机械化）** the entire lunch process. The cafeteria manager immediately grabbed the soup pot, afraid the tomato soup might be automatically poured into a stapler next.",
      "The busiest place of all was the \"super test station\" outside the nurse's office. On the table stood a **thermometer（温度计）** and a **speedometer（速度计）**, ready to give runners a complete checkup. The biology teacher had been explaining that **pathology（病理学）** was the study of disease, but everyone got distracted by a little dog in the corner receiving **sympathy（同情）** from its friends after a fall. By the time the principal tried to demonstrate speed and nearly fell into the flowerbed, the scene looked so comically **pathetic（又可怜又好笑）** that even the teachers bent over laughing."
    ]
  },
  "scholastic-g5-g5-u1-w19": {
    title: "Unit 19 Story",
    paragraphs: [
      "On Acronym Day, the technology group filled the auditorium with bizarre devices before school had even properly started. The cafeteria manager even brought in a bottle of **canola（菜籽油）** oil and said it might help keep the robot joints moving. When the lights dimmed, a **laser（激光）** beam wrote \"No boring allowed today\" directly onto the blackboard, making the students in the front row think aliens had finally come to observe English class.",
      "In the computer corner, an old **modem（调制解调器）** hummed and struggled to connect, like an elderly man sneezing while working. The astronomy group showed off a **quasar（类星体）** poster and carefully explained that some things in the universe were unbelievably bright. Nearby, the **radar（雷达）** model insisted it was best at detecting faraway objects, while the **sonar（声呐）** model argued that underwater it was the true champion. The two nearly turned the display table into a debate stage.",
      "The chaos reached its peak when the diving club appeared. Their mascot, dressed in full **scuba（水肺潜水装备）** gear, somehow got stuck in the window frame. The broadcasting room instantly announced that this was a textbook **snafu（大混乱）**. Vice Principal Carter, today's **veep（副手）**, ran all over the auditorium in panic and then accidentally **zip（拉上）**ped his jacket onto the microphone stand while turning around. Everyone laughed and agreed that acronyms might be short, but the trouble they caused was definitely not."
    ]
  },
  "scholastic-g5-g5-u1-w20": {
    title: "Unit 20 Story",
    paragraphs: [
      "On English Culture Week, the principal suddenly announced that the whole school would spend a day using British expressions. A **chemist（药店）** sign appeared outside the nurse's office, and the **cupboard（橱柜）** that usually stored brooms and textbooks was relabeled in neat English. Even the teapot inside somehow seemed more elegant. Everyone kept smiling quietly and guessing what place would be renamed next.",
      "After second period, the school radio kept reminding us to say **cutlery（餐具）** instead of simply forks and knives, to pretend the little reading corner at the back of the classroom was a **flat（公寓）**, and to refer to Friday's fun time as a **holiday（假期）** moment. The cafeteria manager got so excited that she renamed the storage room the **larder（食品储藏室）** and invited everyone to take a makeshift **lift（电梯）** to the second floor for British pudding. The whole school felt as though it had turned into a walking vocabulary book.",
      "The strangest part came when the kindergarten teacher borrowed a **pram（婴儿车）** to carry the principal's speech papers, only to find it already occupied by a rolling **nappy（尿布）**. Before dismissal, everyone was invited to ride the tiny \"**underground（地铁）** experience train,\" which simply circled the playground three times and stopped at the cafeteria. Watching everyone laugh, the principal finally admitted that whether the word was British or American, the most important phrase on campus would always be: go eat first."
    ]
  },
  "scholastic-g5-g5-u1-w21": {
    title: "Unit 21 Story",
    paragraphs: [
      "At the opening of Word Origin Week, the principal stepped onto the stage carrying a school magazine with gold edges from the **academy（学校；学园）**, followed by the librarian holding a thick **album（相册）**. The strange thing was that when the album was opened, the class photos inside actually changed their poses by themselves, as if none of them wanted to stay ordinary pictures.",
      "While everyone was staring in amazement, a sudden **cyclone（旋风）** swept across the playground and sent the **dahlia（大丽花）** flowers flying out of the flowerbeds. The cafeteria manager leaned out of the window with a bottle of **ketchup（番茄酱）** and shouted for everyone not to spill lunch on the flowers. The dance teacher, still wearing a **leotard（紧身舞衣）**, ran out to help, making the whole scene look like a live play called Teachers Versus the Wind.",
      "When the wind finally calmed a little, the language teacher held up a **manuscript（手稿）** and continued explaining the origins of words. The biology teacher reminded us that we all needed **oxygen（氧气）** every day, while the geography teacher pointed at the **volcano（火山）** model in the corner and warned everyone not to get too close or it might explode into colored paper again. Just when it seemed the lesson might finally end peacefully, the principal spun around in a wonderfully **zany（滑稽古怪地）** way and flung an entire box of crayons into the air. The class unanimously decided that what they would remember most was not only the word origins, but also the principal's impossible entrance."
    ]
  },
  "scholastic-g5-g5-u1-w22": {
    title: "Unit 22 Story",
    paragraphs: [
      "Prefix Day had barely begun when the broadcasting room interrupted the principal with a **retroactive（追溯生效的）** notice saying that anyone who had forgotten homework yesterday now had to hand in an apology today as well. Noah immediately cried out that the rule was completely **irrational（不理性的）**, because yesterday was already over. The class had not even finished arguing when a crash of chairs came from the back door.",
      "A monkey wearing a bow tie had burst into the auditorium and was trying to **abduct（绑走）** the class trophy from the stage. The PE teacher ran after it, but Ethan raised his hand and announced that he would **abstain（弃权；不参与）** from the chase because his shoelaces were tied in such a knot that he would fall after two steps. While everyone was running after the monkey, the cardboard **intersection（交叉路口）** model in the middle of the hall suddenly spun in a new direction, and the vice principal had to **interpose（插到中间）** himself to restore order like a traffic officer at rush hour.",
      "The worst part was still to come. The projector, which already liked to **malfunction（失灵）** from time to time, suddenly cast the image of a **malformed（畸形的）** purple dragon on the wall, scattering the whole class at once. When things finally calmed down, the teacher led us through a **retrospective（回顾）**, and the classroom cleanup captain admitted in embarrassment that he had been terribly **irresponsible（不负责任的）** because while everyone else was rescuing the event, he had been crouching on the floor trying to save his popcorn. The principal sighed and said only one thing: on some days, prefixes are more exciting than the events themselves."
    ]
  },
  "scholastic-g5-g5-u1-w23": {
    title: "Unit 23 Story",
    paragraphs: [
      "The school decided to upgrade the science prefix fair into a **biannual（每年两次的）** event, and the applause in the auditorium almost shook the curtains sideways. The ocean team went first and brought up a **bivalve（双壳贝）** puppet that opened and shut its shell while greeting everyone in a perfectly serious voice, like a clamshell version of a talk-show host.",
      "During the second presentation, Lucas walked over to **commiserate（表示同情）** with a robot that had failed to win the creativity prize. His words sounded sincere, but while talking he quietly **compile（收集整理）**d the robot's fallen screws and stickers into his own backpack. At the same time, the physics teacher was demonstrating a **hydroelectric（水力发电的）** model when a toy **hydroplane（水上飞机）** suddenly skimmed across the sink and almost crashed into the principal's iced tea.",
      "That finally made the principal put on a serious face. He reminded everyone that taking other people's things was **illegal（非法的；不合规的）**, and no one could pretend to be **illiterate（不识字的）** and ignore the lost-and-found sign. Later the broadcasting room read out the prize list in a flat **monotone（单调的声音）**, each name as short and sharp as a **monosyllable（单音节词）**. Even so, the applause on the playground lasted a long time, because everyone knew that the thing they would remember best was not the prize list, but the tiny plane that had almost flown into the principal's drink."
    ]
  },
  "scholastic-g5-g5-u1-w24": {
    title: "Unit 24 Story",
    paragraphs: [
      "Before the end-of-term awards ceremony even began, the principal received an **accusation（指控）** saying that the cookies in the teachers' office had mysteriously disappeared during the night. By perfect chance, a parent who was at school to give a health talk and happened to be a **dentist（牙医）** had not yet left, so everyone immediately chose him to become the \"Cookie Detective.\" After all, if he could notice small tooth problems, surely he could notice cookie clues.",
      "Before the case could be solved, another disaster struck the auditorium. One corner of the banner hanging above the stage suddenly came loose, and a hamster rushed forward and held the rope with both paws in a scene so **heroic（英勇的）** that the school history teacher declared it one of the most **historic（有历史意义的）** moments in campus memory. The broadcasting room instantly sent over the **journalism（新闻报道）** team to interview the hamster as if it deserved its own press conference.",
      "Halfway through the interview, our **perfectionist（完美主义者）** student council rep began frowning and complaining that the whole ceremony had become too messy. He suggested that everyone go calm down in the **recreation（娱乐活动区）** area. Outside, a **succulent（多汁植物）** in the flowerbed swayed wildly in the wind, and the atmosphere inside and outside the hall became slightly **turbulent（动荡的）**. Still, the principal insisted on keeping his **optimism（乐观）**, saying that as long as the cookies had not really been eaten, the day could still be saved. In the end, the truth turned out to be simple: the guard had locked the cookies in a filing cabinet and forgotten to mention it. The whole auditorium burst into laughter, and everyone agreed that the Cookie Case made a better grand finale than any official program."
    ]
  }
};
